image: python:3.8.19-bookworm

stages:
  - test
  - deploy

before_script:
  - echo "Running before script"
  - echo "Installing requirements..."
  - pip install -r $CI_PROJECT_DIR/requirements.txt
  
test:
  stage: test
  script:
    - echo "Executing tests..."
    - pytest ./tests/test_experiments.py
    - pytest ./tests/test_analysis_single.py
    - pytest ./tests/test_analysis_multi.py

deploy:
  stage: deploy
  script:
    - echo "No deployment commands for now."