stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"
job_test:
  stage: test
  script:
    - echo "Running tests"
job_test_exp:
  stage: test
  script:
    - pip install -r requirements.txt
    - python run.py -e 5

