version: '0.1'

services:
  carla:
    image: carlasim/carla:0.9.13
    container_name: carla
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/recordings:/tmp/recordings:rw
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: /bin/bash ./CarlaUE4.sh -RenderOffScreen
